project:
  type: website
  pre-render: ./scripts/past_perfect_read_data.R
  output-dir: docs

website:
  title: ""
  search:
    location: navbar
    type: textbox
  navbar:
    background: light
    left: 
      - href: https://univmuseum.nmsu.edu/
        text: University Museum
    right:

      - href: index.qmd
        text: Main Pottery Listing
  page-footer:
    left: "*Pottery from the Americas*"
    right: "[NMSU University Museum](https://univmuseum.nmsu.edu/)"
    background: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

execute:
  freeze: false

editor: source

