project:
  type: website
  pre-render: ./scripts/past_perfect_read_data.R
  output-dir: docs

website:
  title: ""
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Main Pottery Listing
  page-footer:
    left: "*Pottery from the Americas*"
    right: "NMSU University Museum"
    background: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

execute:
  freeze: false

editor: source

