project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Pottery Listing


format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: source

