project:
  type: website
  pre-render: ./scripts/build.R
  output-dir: docs

website:
  title: "*Pottery from the Americas*"
  search:
    location: navbar
    type: textbox
  navbar:
    background: light
    left: 
      - finding_guide.qmd
  page-footer:
    left: "*Pottery from the Americas*"
    right: "[NMSU University Museum](https://univmuseum.nmsu.edu/)"
    background: light

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

execute:
  freeze: false

editor: source

