project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Main Listing


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

